# Generated by Django 5.1.6 on 2025-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('added_field', 'Added Field'), ('removed_field', 'Removed Field'), ('modified_field', 'Modified Field')], max_length=50)),
                ('model_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
